Models/Tbl_IssueBook.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libray_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IssueBook
    {
        public int issueid { get; set; }
        public int userid { get; set; }
        public int bookid { get; set; }
        public int issuecopy { get; set; }
        public System.DateTime issuedate { get; set; }
        public System.DateTime returndate { get; set; }
        public bool status { get; set; }
        public string description { get; set; }
        public bool reserveNoOfBook { get; set; }
    
        public virtual Tbl_Book Tbl_Book { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}

Controllers/ReserveBookController.cs
using libray_management_system.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace libray_management_system.Controllers
{
    public class ReserveBookController : Controller
    {
        private DBLibraryEntities db = new DBLibraryEntities();

        public static string Message { get; set; }
        public ActionResult Index()
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("login", "Login");
            }
            ViewBag.Message = Message;
            Message = string.Empty;
            var books = db.Tbl_Book.ToList();
            return View(books);
        }
        public ActionResult ReserveBook(int? id, Tbl_Book bb)
        {
            var book = db.Tbl_Book.Find(id);
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("login", "Login");

            }

            int userid = Convert.ToInt32(Convert.ToString(Session["userid"]));
            var issuebooktable = new Tbl_IssueBook()
            {
                bookid = book.bookid,
                description = "Reserve Request",
                issuecopy = 1,
                issuedate = DateTime.Now,
                returndate = DateTime.Now.AddDays(2),
                status = false,
                reserveNoOfBook = true,
                userid = userid
            };
            issuebooktable.userid = userid;
            if (ModelState.IsValid)
            {
                var find = db.Tbl_IssueBook.Where(t => t.returndate >= DateTime.Now && t.bookid == issuebooktable.bookid && (t.status == true || t.reserveNoOfBook == true)).ToList();
                int issuebooks = 0;
                foreach (var item in find)
                {
                    issuebooks = issuebooks + item.issuecopy;
                }
                var stockbooks = db.Tbl_Book.Where(b => b.bookid == issuebooktable.bookid).FirstOrDefault();
                stockbooks.availablestock = stockbooks.availablestock - issuebooktable.issuecopy;
                //stockbooks.isbnnumber = bb.isbnnumber;
                //db.books.Add(stockbooks);
                db.Entry(stockbooks).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                if ((issuebooks == stockbooks.availablestock) || (issuebooks + issuebooktable.issuecopy > stockbooks.availablestock))
                {
                    Message = "Stock is empty";
                    return RedirectToAction("index");
                }
                db.Tbl_IssueBook.Add(issuebooktable);
                db.SaveChanges();
                Message = "Book issue successfully";
                return RedirectToAction("Index");
            }

            ViewBag.bookid = new SelectList(db.Tbl_Book, "bookid", "bookname", issuebooktable.bookid);
            ViewBag.userid = new SelectList(db.Tbl_User, "userid", "username", issuebooktable.userid);
            return RedirectToAction("BookDetail");

        }
    
}
}

Controllers/ReturnBookController.cs
using libray_management_system.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace libray_management_system.Controllers
{
    public class ReturnBookController : Controller
    {
        // GET: ReturnBook
        private DBLibraryEntities db = new DBLibraryEntities();

        public ActionResult ReturnHishory()
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("login", "Login");
            }
            var returnbook = db.Tbl_ReturnBook.ToList();
            return View(returnbook);
        }
    }
}

Controllers/Tbl_IssueBookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using libray_management_system.Models;

namespace libray_management_system.Controllers
{
    public class Tbl_IssueBookController : Controller
    {
        private DBLibraryEntities db = new DBLibraryEntities();

        // GET: Tbl_IssueBook
        public ActionResult IssueBook()
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var tblissues = db.Tbl_IssueBook.Include(t => t.Tbl_Book).Include(t => t.Tbl_User).Where(t => t.status == true && t.reserveNoOfBook == false);
            return View(tblissues.ToList());
        }
        public ActionResult ReserveBook()
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Login", "Login");
            }

            var tblissues = db.Tbl_IssueBook.Include(t => t.Tbl_Book).Include(t => t.Tbl_User).Where(t => t.status == false && t.reserveNoOfBook == true && t.returndate > DateTime.Now);

            return View(tblissues.ToList());
        }

        public ActionResult ApproveRequest(int? id)
        {
            var request = db.Tbl_IssueBook.Find(id);
            request.reserveNoOfBook = false;
            request.status = true;
            request.description = "Approve";
            db.Entry(request).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("ReserveBook");
        }
        public ActionResult ReturnPendingBook()
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            List<Tbl_IssueBook> list = new List<Tbl_IssueBook>();
            var tbl_issuebook = db.Tbl_IssueBook.Where(t => t.status == true && t.reserveNoOfBook == false).ToList();
            foreach (var item in tbl_issuebook)
            {
                var returndate = item.returndate;
                int noOfdays = (returndate - DateTime.Now).Days;
                if (noOfdays <= 3)
                {
                    list.Add(new Tbl_IssueBook
                    {
                        bookid = item.bookid,
                        Tbl_Book = item.Tbl_Book,
                        description = item.description,
                        issueid = item.issueid,
                        issuecopy = item.issuecopy,
                        issuedate = item.issuedate,
                        reserveNoOfBook = item.reserveNoOfBook,
                        returndate = item.returndate,
                        status = item.status,
                        userid = item.userid,
                        Tbl_User = item.Tbl_User
                    }
                        );
                }
            }
            return View(list.ToList());
        }

        public ActionResult ReturnBook(int? id)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
           
            int userid = Convert.ToInt32(Convert.ToString(Session["userid"]));
            var book = db.Tbl_IssueBook.Find(id);
            int fine = 0;
            var returndate = book.returndate;
            int noOfdays = (DateTime.Now - returndate).Days;

            if (book.status == true && book.reserveNoOfBook == false)
            {
                if (noOfdays > 0)
                {
                    fine = 5 * noOfdays;
                }
                var returnbook = new Tbl_ReturnBook()
                {
                    bookid = book.bookid,
                    currentdate = DateTime.Now,
                    issuedate = book.issuedate,
                    returndate = book.returndate,
                    userid = book.userid,
                };
                var stockbooks = db.Tbl_Book.Where(b => b.bookid == returnbook.bookid).FirstOrDefault();
                stockbooks.availablestock = stockbooks.availablestock + 1;
                //stockbooks.isbnnumber = bb.isbnnumber;
                //db.books.Add(stockbooks);
                db.Entry(stockbooks).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                db.Tbl_ReturnBook.Add(returnbook);
                db.SaveChanges();
            }
            book.status = false;
            book.reserveNoOfBook = false;
            db.Entry(book).State = EntityState.Modified;
            db.SaveChanges();
            if (fine > 0)
            {
                var addfine = new Tbl_BookFine()
                {
                    bookid = book.bookid,
                    fineamount = fine,
                    finedate = DateTime.Now,
                    NoOfDays = noOfdays,
                    receiveamount = 0,
                    userid = userid

                };
                db.Tbl_BookFine.Add(addfine);
                db.SaveChanges();
            }
            return RedirectToAction("IssueBook","Tbl_IssueBook");



        }

        // GET: tblissues/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_IssueBook tblissue = db.Tbl_IssueBook.Find(id);
            if (tblissue == null)
            {
                return HttpNotFound();
            }
            return View(tblissue);
        }

        // GET: tblissues/Create
        public ActionResult Create()
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            ViewBag.bookid = new SelectList(db.Tbl_Book, "bookid", "bookname", "0");
            ViewBag.userid = new SelectList(db.Tbl_User, "userid", "uniquename", "0");
            return View();
        }

        // POST: tblissues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tbl_IssueBook tblissue, Tbl_Book bok)
        {
            //if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            //{
            //    return RedirectToAction("login","Home");

            //}

            int userid = Convert.ToInt32(Convert.ToString(Session["userid"]));
            tblissue.userid = userid;
            if (ModelState.IsValid)
            {
                var find = db.Tbl_IssueBook.Where(t => t.returndate >= DateTime.Now && t.bookid == tblissue.bookid && (t.status == true || t.reserveNoOfBook == true)).ToList();
                int issuebooks = 0;
                foreach (var item in find)
                {
                    issuebooks = issuebooks + item.issuecopy;
                }
                var stockbooks = db.Tbl_Book.Where(b => b.bookid == tblissue.bookid).FirstOrDefault();
                if ((issuebooks == stockbooks.availablestock) || (issuebooks + tblissue.issuecopy > stockbooks.availablestock))
                {
                    ViewBag.Message = "Stock is empty";
                    return View(tblissue);
                }
                db.Tbl_IssueBook.Add(tblissue);

                db.SaveChanges();
                ViewBag.Message = "Book issue successfully";
                return RedirectToAction("Index");
            }

            ViewBag.bookid = new SelectList(db.Tbl_Book, "bookid", "bookname", tblissue.bookid);
            ViewBag.userid = new SelectList(db.Tbl_User, "userid", "username", tblissue.userid);
            return View(tblissue);
        }

        // GET: tblissues/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_IssueBook tblissue = db.Tbl_IssueBook.Find(id);
            if (tblissue == null)
            {
                return HttpNotFound();
            }
            ViewBag.bookid = new SelectList(db.Tbl_Book, "bookid", "bookname", tblissue.bookid);
            ViewBag.userid = new SelectList(db.Tbl_User, "userid", "username", tblissue.userid);
            return View(tblissue);
        }

        // POST: tblissues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "issueid,userid,bookid,issuecopy,issuedate,returendate,status,description,reserveNoOfBook")] Tbl_IssueBook tblissue)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblissue).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.bookid = new SelectList(db.Tbl_Book, "bookid", "bookname", tblissue.bookid);
            ViewBag.userid = new SelectList(db.Tbl_User, "userid", "uniquename", tblissue.userid);
            return View(tblissue);
        }

        // GET: tblissues/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_IssueBook tblissue = db.Tbl_IssueBook.Find(id);
            if (tblissue == null)
            {
                return HttpNotFound();
            }
            return View(tblissue);
        }

        // POST: tblissues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

Views/Tbl_IssueBook/IssueBook.cshtml
@model IEnumerable<libray_management_system.Models.Tbl_IssueBook>
@*@using PagedList.Mvc
@model PagedList.IPagedList<libray_management_system.Models.Tbl_IssueBook>*@


@{
    ViewBag.Title = "IssueBook";
    Layout = "~/Views/_LayoutPage2.cshtml";
}


<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Online Library Management System | Manage Publisher</title>
    <!-- BOOTSTRAP CORE STYLE  -->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONT AWESOME STYLE  -->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- DATATABLE STYLE  -->
    <link href="~/assets/js/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
    <!-- CUSTOM STYLE  -->
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

</head>
<body>
    @using (Html.BeginForm())
    {
        <style>
            body {
                width: 80%
            }

            table {
                width: 60%;
                border-collapse: collapse;
            }

                table tr {
                    border: solid thin;
                }

                    table tr td {
                        width: 20%;
                    }

            #pager {
                padding-left: 5%;
            }

                #pager p {
                    margin-left: 5%;
                }
        </style>
        <!------MENU SECTION START-->
        <div class="main-content">

            <div class="content-wrapper">
                <div class="container">
                    <div class="row pad-botm">
                        <div class="col-md-12">

                        </div>


                    </div>


                </div>
                <div class="row">
                    <div class="col-md-12">
                        <!-- Advanced Tables -->
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <div class="table-responsive">
                                    <h4 class="header-line">All Issue Book</h4>

                                    <div class="panel-heading">

                                    </div>

                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example" align="center">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Book Name</th>
                                                <th>UserName</th>

                                                <th>User Email</th>
                                                <th>IssueCopy</th>
                                                <th>IssueDate</th>


                                                <th>ReturnDate</th>
                                                <th>Status</th>
                                                <th>Description</th>
                                                <th>Reserve</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>


                                            @foreach (var item in Model)
                                            {
                                                <tr class="odd gradeX">
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.issueid)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.Tbl_Book.bookname)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.Tbl_User.username)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.Tbl_User.emailid)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.issuecopy)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.issuedate)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.returndate)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.status)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.description)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.reserveNoOfBook)
                                                    </td>

                                                    <td class="center">
                                                        <button class="btn btn-primary"><i class="fa fa-edit "></i>  @Html.ActionLink("Return Book", "ReturnBook", new { id = item.issueid }) |</button>
                                                    </td>


                                                </tr>
                                            }

                                        </tbody>
                                    </table>

                                    @*<div id="pager">
                                        <p> Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>
                                        <span style=" color: black; float: left; padding: 8px 16px; background-color:cornflowerblue"> @Html.PagedListPager(Model, page => Url.Action("index", new { page }))</span>
                                    </div>*@
                                </div>

                            </div>
                        </div>
                        <!--End Advanced Tables -->
                    </div>
                </div>



            </div>
        </div>


        <?php include('includes/footer.php');?>
        <!-- FOOTER SECTION END-->
        <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
        <!-- CORE JQUERY  -->
        <script src="~/assets/js/jquery-1.10.2.js"></script>
        <!-- BOOTSTRAP SCRIPTS  -->
        <script src="~/assets/js/bootstrap.js"></script>
        <!-- DATATABLE SCRIPTS  -->
        <script src="~/assets/js/dataTables/jquery.dataTables.js"></script>
        <script src="~/assets/js/dataTables/dataTables.bootstrap.js"></script>
        <!-- CUSTOM SCRIPTS  -->
        <script src="~/assets/js/custom.js"></script>
    }
</body>
</html>

Views/Tbl_IssueBook/ReturnPendingBook.cshtml
@model IEnumerable<libray_management_system.Models.Tbl_IssueBook>

@{
    ViewBag.Title = "ReturnPendingBook";
    Layout = "~/Views/_LayoutPage2.cshtml";
}


<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Online Library Management System | Manage Publisher</title>
    <!-- BOOTSTRAP CORE STYLE  -->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONT AWESOME STYLE  -->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- DATATABLE STYLE  -->
    <link href="~/assets/js/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
    <!-- CUSTOM STYLE  -->
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

</head>
<body>
    @using (Html.BeginForm())
    {
        <style>
            body {
                width: 80%
            }

            table {
                width: 60%;
                border-collapse: collapse;
            }

                table tr {
                    border: solid thin;
                }

                    table tr td {
                        width: 20%;
                    }

            #pager {
                padding-left: 5%;
            }

                #pager p {
                    margin-left: 5%;
                }
        </style>
        <!------MENU SECTION START-->
        <div class="main-content">

            <div class="content-wrapper">
                <div class="container">
                    <div class="row pad-botm">
                        <div class="col-md-12">

                        </div>


                    </div>


                </div>
                <div class="row">
                    <div class="col-md-12">
                        <!-- Advanced Tables -->
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <div class="table-responsive">
                                    <h4 class="header-line">Return PendingBook</h4>

                                    <div class="panel-heading">

                                    </div>

                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example" align="center">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Book Name</th>
                                                <th>UserName</th>
                                                <th>User Email</th>
                                                <th>IssueCopy</th>

                                                <th>IssueDate</th>
                                                <th>ReturnDate</th>
                                                <th>Status</th>
                                                <th>Description</th>
                                                <th>Reserve</th>
                                            </tr>
                                        </thead>
                                        <tbody>



                                            @foreach (var item in Model)
                                            {
                                                <tr class="odd gradeX">
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.issueid)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.Tbl_Book.bookname)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.Tbl_User.username)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.Tbl_User.emailid)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.issuecopy)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.issuedate)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.returndate)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.status)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.description)
                                                    </td>
                                                    <td class="center">
                                                        @Html.DisplayFor(modelItem => item.reserveNoOfBook)
                                                    </td>

                                                    <td class="center">
                                                        @Html.ActionLink("Return Book", "ReturnBook", new { id = item.issueid }, new { @class = "btn btn-primary" }) |
                                                    </td>


                                                </tr>
                                            }

                                        </tbody>
                                    </table>

                                    @*<div id="pager">
                                            <p> Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>
                                            <span style=" color: black; float: left; padding: 8px 16px; background-color:cornflowerblue"> @Html.PagedListPager(Model, page => Url.Action("index", new { page }))</span>
                                        </div>*@
                                </div>

                            </div>
                        </div>
                        <!--End Advanced Tables -->
                    </div>
                </div>



            </div>
        </div>


        <?php include('includes/footer.php');?>
        <!-- FOOTER SECTION END-->
        <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
        <!-- CORE JQUERY  -->
        <script src="~/assets/js/jquery-1.10.2.js"></script>
        <!-- BOOTSTRAP SCRIPTS  -->
        <script src="~/assets/js/bootstrap.js"></script>
        <!-- DATATABLE SCRIPTS  -->
        <script src="~/assets/js/dataTables/jquery.dataTables.js"></script>
        <script src="~/assets/js/dataTables/dataTables.bootstrap.js"></script>
        <!-- CUSTOM SCRIPTS  -->
        <script src="~/assets/js/custom.js"></script>
    }
</body>
</html>