Controllers/ReserveBookController.cs
using libray_management_system.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace libray_management_system.Controllers
{
    public class ReserveBookController : Controller
    {
        private DBLibraryEntities db = new DBLibraryEntities();

        public static string Message { get; set; }
        public ActionResult Index()
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("login", "Login");
            }
            ViewBag.Message = Message;
            Message = string.Empty;
            var books = db.Tbl_Book.ToList();
            return View(books);
        }
        public ActionResult ReserveBook(int? id, Tbl_Book bb)
        {
            var book = db.Tbl_Book.Find(id);
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("login", "Login");

            }

            int userid = Convert.ToInt32(Convert.ToString(Session["userid"]));
            var issuebooktable = new Tbl_IssueBook()
            {
                bookid = book.bookid,
                description = "Reserve Request",
                issuecopy = 1,
                issuedate = DateTime.Now,
                returndate = DateTime.Now.AddDays(2),
                status = false,
                reserveNoOfBook = true,
                userid = userid
            };
            issuebooktable.userid = userid;
            if (ModelState.IsValid)
            {
                var find = db.Tbl_IssueBook.Where(t => t.returndate >= DateTime.Now && t.bookid == issuebooktable.bookid && (t.status == true || t.reserveNoOfBook == true)).ToList();
                int issuebooks = 0;
                foreach (var item in find)
                {
                    issuebooks = issuebooks + item.issuecopy;
                }
                var stockbooks = db.Tbl_Book.Where(b => b.bookid == issuebooktable.bookid).FirstOrDefault();
                stockbooks.availablestock = stockbooks.availablestock - issuebooktable.issuecopy;
                //stockbooks.isbnnumber = bb.isbnnumber;
                //db.books.Add(stockbooks);
                db.Entry(stockbooks).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                if ((issuebooks == stockbooks.availablestock) || (issuebooks + issuebooktable.issuecopy > stockbooks.availablestock))
                {
                    Message = "Stock is empty";
                    return RedirectToAction("index");
                }
                db.Tbl_IssueBook.Add(issuebooktable);
                db.SaveChanges();
                Message = "Book issue successfully";
                return RedirectToAction("Index");
            }

            ViewBag.bookid = new SelectList(db.Tbl_Book, "bookid", "bookname", issuebooktable.bookid);
            ViewBag.userid = new SelectList(db.Tbl_User, "userid", "username", issuebooktable.userid);
            return RedirectToAction("BookDetail");

        }
    
}
}

Views/ReserveBook/Index.cshtml
@model IEnumerable<libray_management_system.Models.Tbl_Book>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_LayoutPage2.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.bookname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.publisheryear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.edition)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bookimae)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.availablestock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.totalstok)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isbnnumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.accessionNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.regdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tbl_Author.authorname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tbl_Category.categoryname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tbl_Department.departmentname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tbl_Publisher.publishername)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.bookname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.publisheryear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.edition)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.bookimae)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.availablestock)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.totalstok)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isbnnumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.accessionNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.regdate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tbl_Author.authorname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tbl_Category.categoryname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tbl_Department.departmentname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tbl_Publisher.publishername)
        </td>
        <td>
            @Html.ActionLink("Reserve Book", "ReserveBook", new { id = item.bookid }, new { @class = "btn btn-success" }) |

        </td>
    </tr>
}

</table>